Repository Do-it-Together-DoTo/DoTo_Back, pull requests merged in 2024-07, with the labels that each got.

#163 feat : redis transaction 적용
  src/main/java/site/doto/global/config/RedisConfig.java
  src/main/java/site/doto/global/config/SecurityConfig.java
  src/main/resources/application-local.yml
  src/test/java/site/doto/BaseTest.java
  src/test/java/site/doto/domain/category/controller/CategoryControllerTest.java
  src/test/java/site/doto/domain/relation/controller/RelationControllerTest.java
  src/test/resources/application.yml
Labels: ✨ feat

#161 feat : Todo 또하기 API 구현 및 테스트
  src/main/java/site/doto/domain/todo/controller/TodoController.java
  src/main/java/site/doto/domain/todo/dto/TodoAddReq.java
  src/main/java/site/doto/domain/todo/dto/TodoRedoReq.java
  src/main/java/site/doto/domain/todo/service/TodoService.java
  src/test/java/site/doto/domain/todo/controller/TodoControllerTest.java
Labels: ✨ feat, ✅ test

#167 fix : DateFormat 수정
  src/main/java/site/doto/domain/todo/dto/TodoListReq.java
  src/main/java/site/doto/domain/todo/dto/TodoModifyReq.java
  src/main/resources/sql/data-dev.sql
  src/main/resources/sql/data.sql
  src/test/java/site/doto/domain/category/controller/CategoryControllerTest.java
  src/test/java/site/doto/domain/todo/controller/TodoControllerTest.java
  src/test/resources/sql/data.sql
Labels: 🐛 fix

#168 feat : 로그인 response 데이터 추가
  src/main/java/site/doto/domain/member/controller/MemberController.java
  src/main/java/site/doto/domain/member/dto/LoginRes.java
  src/test/java/site/doto/domain/member/controller/MemberControllerTest.java
Labels: ✨ feat

#169 feat : 투두 개수 조회 mock 추가
  src/main/java/site/doto/domain/todo/controller/TodoController.java
  src/main/java/site/doto/domain/todo/dto/TodoCountDto.java
  src/main/java/site/doto/domain/todo/dto/TodoCountReq.java
  src/main/java/site/doto/domain/todo/dto/TodoCountRes.java
  src/main/java/site/doto/global/status_code/SuccessCode.java
  src/test/java/site/doto/domain/todo/controller/TodoControllerTest.java
Labels: ✨ feat, ✅ test

#170 feat : 차단 유저 목록 API 구현 및 테스트 작성
  src/main/java/site/doto/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/site/doto/domain/member/repository/MemberRepositoryCustomImpl.java
  src/main/java/site/doto/domain/relation/controller/RelationController.java
  src/main/java/site/doto/domain/relation/dto/RelationBlockListRes.java
  src/main/java/site/doto/domain/relation/dto/RelationListRes.java
  src/main/java/site/doto/domain/relation/service/RelationService.java
  src/main/resources/sql/data-dev.sql
  src/main/resources/sql/data.sql
  src/test/java/site/doto/domain/relation/controller/RelationControllerTest.java
  src/test/resources/sql/data.sql
Labels: ✨ feat, ✅ test

#174 feat : Todo 완료 여부 API 구현 및 테스트 추가
  src/main/java/site/doto/domain/todo/controller/TodoController.java
  src/main/java/site/doto/domain/todo/entity/Todo.java
  src/main/java/site/doto/domain/todo/service/TodoService.java
  src/main/java/site/doto/global/status_code/SuccessCode.java
  src/test/java/site/doto/domain/todo/controller/TodoControllerTest.java
Labels: ✨ feat, ✅ test

#177 feat : 활성화 카테고리 1개 미만 시 예외처리 추가
  src/main/java/site/doto/domain/category/service/CategoryService.java
  src/main/java/site/doto/global/status_code/ErrorCode.java
Labels: ✨ feat

#180 feat : 내 정보 조회 api 구현
  src/main/java/site/doto/domain/item/controller/ItemController.java
  src/main/java/site/doto/domain/item/dto/ItemDto.java
  src/main/java/site/doto/domain/member/controller/MemberController.java
  src/main/java/site/doto/domain/member/service/MemberService.java
  src/test/java/site/doto/domain/item/controller/ItemControllerTest.java
Labels: ✨ feat

#182 feat : 웹소켓 및 레디스 설정 추가
  src/main/java/site/doto/domain/chat/controller/ChatController.java
  src/main/java/site/doto/domain/chat/dto/ChatDto.java
  src/main/java/site/doto/global/config/RedisConfig.java
  src/main/java/site/doto/global/config/SecurityConfig.java
  src/main/java/site/doto/global/config/WebSocketConfig.java
  src/main/java/site/doto/global/redis/RedisPublisher.java
  src/main/java/site/doto/global/redis/RedisSubscriber.java
  src/test/java/site/doto/domain/chat/controller/ChatControllerTest.java
Labels: ✨ feat

#181 feat : 유저 검색 API 구현 및 테스트 작성
  src/main/java/site/doto/domain/member/controller/MemberController.java
  src/main/java/site/doto/domain/member/dto/MemberSearchDto.java
  src/main/java/site/doto/domain/member/dto/MemberSearchReq.java
  src/main/java/site/doto/domain/member/dto/MemberSearchRes.java
  src/main/java/site/doto/domain/member/dto/MembersSearchDto.java
  src/main/java/site/doto/domain/member/dto/MembersSearchRes.java
  src/main/java/site/doto/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/site/doto/domain/member/repository/MemberRepositoryCustomImpl.java
  src/main/java/site/doto/domain/member/service/MemberService.java
  src/main/java/site/doto/domain/relation/controller/RelationController.java
  src/main/java/site/doto/domain/relation/service/RelationService.java
  src/main/resources/sql/data-dev.sql
  src/main/resources/sql/data.sql
  src/test/java/site/doto/domain/member/controller/MemberControllerTest.java
  src/test/resources/sql/data.sql
Labels: ✨ feat, ✅ test

#183 fix : 중복된 MemberService 선언 삭제
  src/main/java/site/doto/domain/member/controller/MemberController.java
  src/main/java/site/doto/domain/member/service/MemberService.java
Labels: 🐛 fix

#184 fix : websocket 설정 변경
  src/main/java/site/doto/global/config/WebSocketConfig.java
Labels: 🐛 fix

#186 feat : 참여 중인 채팅방 조회 API 구현
  src/main/java/site/doto/domain/chatroom/controller/ChatRoomController.java
  src/main/java/site/doto/domain/chatroom/dto/ChatRoomDto.java
  src/main/java/site/doto/domain/chatroom/dto/ChatRoomListRes.java
  src/main/java/site/doto/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/site/doto/domain/chatroom/service/ChatRoomService.java
  src/main/java/site/doto/domain/member_chatroom/entity/MemberChatRoom.java
  src/main/resources/sql/data-dev.sql
  src/main/resources/sql/data.sql
  src/test/resources/sql/data.sql
Labels: ✨ feat

#190 feat : 나의 아이템 전체 조회 API 구현
  src/main/java/site/doto/domain/item/controller/ItemController.java
  src/main/java/site/doto/domain/item/entity/Item.java
  src/main/java/site/doto/domain/item/repository/ItemRepository.java
  src/main/java/site/doto/domain/item/service/ItemService.java
  src/main/resources/sql/data-dev.sql
  src/main/resources/sql/data.sql
  src/test/resources/sql/data.sql
Labels: ✨ feat

#194 fix : CORS 설정 변경
  src/main/java/site/doto/global/config/SecurityConfig.java
Labels: 🐛 fix

#192 feat : 채팅방 참여 API 구현 및 테스트 코드 작성
  src/main/java/site/doto/domain/chatroom/controller/ChatRoomController.java
  src/main/java/site/doto/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/site/doto/domain/chatroom/service/ChatRoomService.java
  src/main/java/site/doto/domain/member_chat_room/entity/MemberChatRoom.java
  src/main/java/site/doto/domain/member_chat_room/entity/MemberChatRoomPK.java
  src/main/java/site/doto/domain/member_chat_room/repository/MemberChatRoomRepository.java
  src/main/java/site/doto/global/status_code/ErrorCode.java
  src/test/java/site/doto/domain/chatroom/controller/ChatRoomControllerTest.java
Labels: ✨ feat, ✅ test

#191 feat : 회원 정보 수정 API 구현 및 테스트 작성
  src/main/java/site/doto/domain/member/controller/MemberController.java
  src/main/java/site/doto/domain/member/dto/MemberModifyReq.java
  src/main/java/site/doto/domain/member/dto/MemberModifyRes.java
  src/main/java/site/doto/domain/member/entity/Member.java
  src/main/java/site/doto/domain/member/repository/MemberRepository.java
  src/main/java/site/doto/domain/member/service/MemberService.java
  src/main/java/site/doto/global/status_code/ErrorCode.java
  src/test/java/site/doto/domain/member/controller/MemberControllerTest.java
Labels: ✨ feat, ✅ test
