Repository Do-it-Together-DoTo/DoTo_Back, pull requests merged in 2024-05, with the labels that each got.

#3 feat : Entity 생성 및 매핑 추가
  src/main/java/site/doto/domain/betting/entity/Betting.java
  src/main/java/site/doto/domain/category/entity/Category.java
  src/main/java/site/doto/domain/character/entity/Character.java
  src/main/java/site/doto/domain/character_type/entity/CharacterType.java
  src/main/java/site/doto/domain/chat/entity/Chat.java
  src/main/java/site/doto/domain/chatroom/entity/ChatRoom.java
  src/main/java/site/doto/domain/friend/entity/Friend.java
  src/main/java/site/doto/domain/item/entity/Item.java
  src/main/java/site/doto/domain/item_type/entity/ItemType.java
  src/main/java/site/doto/domain/member/entity/Member.java
  src/main/java/site/doto/domain/member_betting/entity/MemberBetting.java
  src/main/java/site/doto/domain/member_chatroom/entity/MemberChatRoom.java
  src/main/java/site/doto/domain/todo/entity/Todo.java
Labels: ✨ feat

#7 feat : Global Dto 추가
  src/main/java/site/doto/global/common/code/ErrorCode.java
  src/main/java/site/doto/global/common/code/SuccessCode.java
  src/main/java/site/doto/global/common/dto/ApiResponseHeader.java
  src/main/java/site/doto/global/common/dto/ResponseDto.java
  src/main/java/site/doto/global/common/dto/SliceDto.java
Labels: ✨ feat

#8 feat : Redis 설정 추가
  src/main/java/site/doto/Application.java
  src/main/java/site/doto/global/config/CacheConfig.java
  src/main/java/site/doto/global/config/RedisConfig.java
  src/main/java/site/doto/global/redis/RedisUtils.java
Labels: ✨ feat

#11 rename : global 패키지 구조 변경
  src/main/java/site/doto/global/code/ErrorCode.java
  src/main/java/site/doto/global/code/SuccessCode.java
  src/main/java/site/doto/global/dto/ApiResponseHeader.java
  src/main/java/site/doto/global/dto/ResponseDto.java
  src/main/java/site/doto/global/dto/SliceDto.java
  src/main/java/site/doto/global/exception/CustomException.java
  src/main/java/site/doto/global/handler/GlobalExceptionHandler.java
Labels: 🚚 rename

#13 feat : logTrace 추가
  src/main/java/site/doto/global/config/AppConfig.java
  src/main/java/site/doto/global/logtracer/LogTrace.java
  src/main/java/site/doto/global/logtracer/LogTraceAspect.java
  src/main/java/site/doto/global/logtracer/TraceStatus.java
  src/main/resources/application-local.yml
Labels: ✨ feat

#16 feat : p6spy 적용
  build.gradle
  src/main/java/site/doto/global/config/AppConfig.java
  src/main/java/site/doto/global/p6spy/P6spySqlFormatConfiguration.java
  src/main/resources/application-local.yml
Labels: ✨ feat

#17 feat : Spring REST Docs 및 Swagger 설정 추가
  build.gradle
  src/main/java/site/doto/Application.java
Labels: ✨ feat

#20 feat : member sql 삽입 및 memberType 변경
  src/main/java/site/doto/domain/member/entity/Member.java
  src/main/java/site/doto/domain/member/type/MemberType.java
  src/main/resources/application-local.yml
  src/main/resources/sql/member_data.sql
Labels: ✨ feat

#21 feat : 상태코드 정의
  src/main/java/site/doto/global/code/ErrorCode.java
  src/main/java/site/doto/global/code/SuccessCode.java
  src/main/java/site/doto/global/dto/ApiResponseHeader.java
  src/main/java/site/doto/global/dto/ResponseDto.java
  src/main/java/site/doto/global/exception/CustomException.java
  src/main/java/site/doto/global/status_code/ErrorCode.java
  src/main/java/site/doto/global/status_code/SuccessCode.java
Labels: ✨ feat

#26 feat : 멤버 및 카테고리 조회 메소드 추가
  src/main/java/site/doto/domain/category/repository/CategoryRepository.java
  src/main/java/site/doto/domain/member/repository/MemberRepository.java
  src/main/resources/application-local.yml
  src/main/resources/sql/data.sql
  src/main/resources/sql/member_data.sql
Labels: ✨ feat

#28 fix : 정적 리소스를 불러오지 못하는 문제 해결
  build.gradle
  src/main/java/site/doto/global/config/StaticConfig.java
  src/main/java/site/doto/global/handler/GlobalExceptionHandler.java
  src/main/resources/application.yml
Labels: 🐛 fix

#30 chore : gitignore 설정 추가 및 프로젝트 java 버전 변경
  .gitignore
  build.gradle
Labels: 📝 chore

#34 feat : 회원 관련 Dto 및 MockMVC 추가
  src/main/java/site/doto/domain/member/controller/MemberController.java
  src/main/java/site/doto/domain/member/dto/AuthCodeSendReq.java
  src/main/java/site/doto/domain/member/dto/AuthCodeVerifyReq.java
  src/main/java/site/doto/domain/member/dto/LoginReq.java
  src/main/java/site/doto/domain/member/dto/LoginRes.java
  src/main/java/site/doto/domain/member/dto/MemberAddReq.java
  src/main/java/site/doto/domain/member/dto/MemberModifyReq.java
  src/main/java/site/doto/domain/member/dto/MemberModifyRes.java
  src/main/java/site/doto/domain/member/dto/PasswordFindReq.java
  src/main/java/site/doto/domain/member/dto/PasswordModifyReq.java
  src/main/java/site/doto/domain/member/entity/Member.java
  src/test/java/site/doto/member/MemberControllerTest.java
Labels: ✨ feat, ✅ test

#35 feat : Category Mock Api 구현 및 테스트 코드 작성 / 문서화
  src/main/java/site/doto/domain/category/controller/CategoryController.java
  src/main/java/site/doto/domain/category/dto/CategoryAddReq.java
  src/main/java/site/doto/domain/category/dto/CategoryArrangeReq.java
  src/main/java/site/doto/domain/category/dto/CategoryDetailsRes.java
  src/main/java/site/doto/domain/category/dto/CategoryListRes.java
  src/main/java/site/doto/domain/category/dto/CategoryModifyReq.java
  src/main/java/site/doto/domain/category/entity/Category.java
  src/main/java/site/doto/domain/category/enums/Color.java
  src/test/java/site/doto/domain/category/CategoryControllerTest.java
Labels: ✨ feat, ✅ test

#43 refactor : ignore 재설정 및 Entity Referece Type으로 변경
  .gitignore
  .gradle/8.7/checksums/checksums.lock
  .gradle/8.7/checksums/md5-checksums.bin
  .gradle/8.7/checksums/sha1-checksums.bin
  .gradle/8.7/dependencies-accessors/gc.properties
  .gradle/8.7/executionHistory/executionHistory.bin
  .gradle/8.7/executionHistory/executionHistory.lock
  .gradle/8.7/fileChanges/last-build.bin
  .gradle/8.7/fileHashes/fileHashes.bin
  .gradle/8.7/fileHashes/fileHashes.lock
  .gradle/8.7/fileHashes/resourceHashesCache.bin
  .gradle/8.7/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  .gradle/vcs-1/gc.properties
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  gradlew
  src/main/java/site/doto/domain/betting/entity/Betting.java
  src/main/java/site/doto/domain/category/dto/CategoryDetailsRes.java
  src/main/java/site/doto/domain/category/entity/Category.java
  src/main/java/site/doto/domain/character/entity/Character.java
  src/main/java/site/doto/domain/character_type/entity/CharacterType.java
  src/main/java/site/doto/domain/chat/entity/Chat.java
  src/main/java/site/doto/domain/chatroom/entity/ChatRoom.java
  src/main/java/site/doto/domain/friend/entity/Friend.java
  src/main/java/site/doto/domain/item/entity/Item.java
  src/main/java/site/doto/domain/item_type/entity/ItemType.java
  src/main/java/site/doto/domain/member/entity/Member.java
  src/main/java/site/doto/domain/member_betting/entity/MemberBetting.java
  src/main/java/site/doto/domain/todo/dto/TodoDetailsRes.java
  src/main/java/site/doto/domain/todo/entity/Todo.java
Labels: ♻️ refactor
